//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Appraisal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public int ID { get; set; }
        public string Reviewer { get; set; }
        public Nullable<System.DateTime> ReviewDate { get; set; }
        public Nullable<int> AppraisalID { get; set; }
        public Nullable<decimal> Amount { get; set; }
    
        public virtual Property Property { get; set; }
    }
}
